"""Write the timestamped scene narrative and license-provenance credits."""

from __future__ import annotations

import json
from pathlib import Path

from .models import AnalysisResult
from .timecode import edl_timecode


def _tc(seconds: float, fps: float) -> str:
    return edl_timecode(seconds, fps if fps > 0 else 30.0)


def write_narrative(result: AnalysisResult, outdir: str | Path) -> dict[str, Path]:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    json_path = outdir / "scene_narrative.json"
    json_path.write_text(json.dumps(result.to_dict(), indent=2), encoding="utf-8")

    md_path = outdir / "scene_narrative.md"
    md_path.write_text(_render_markdown(result), encoding="utf-8")
    return {"json": json_path, "markdown": md_path}


def _render_markdown(result: AnalysisResult) -> str:
    fps = result.fps or 30.0
    lines: list[str] = [
        f"# Scene narrative — {Path(result.video_path).name}",
        "",
        f"- **Duration:** {result.duration:.2f}s  ·  **fps:** {fps:.3f}  ·  "
        f"**{result.width}×{result.height}**",
        f"- **Backend:** `{result.backend}`  ·  **onsets detected:** {len(result.onsets)}",
        f"- **Cues placed:** {sum(1 for c in result.cues if c.sfx)} / {len(result.cues)}",
        "",
        "## Sound cues",
        "",
        "| Timecode | Event | Conf | Source | Sound | Match |",
        "|----------|-------|------|--------|-------|-------|",
    ]
    for c in result.cues:
        sfx = c.sfx.name if c.sfx else "—"
        mt = f"{c.sfx.match_type} {c.sfx.score:.2f}" if c.sfx else "—"
        lines.append(
            f"| {_tc(c.t, fps)} | {c.event} | {c.confidence:.2f} | {c.source} | {sfx} | {mt} |"
        )

    lines += ["", "## Frame-by-frame narration", ""]
    for obs in result.observations:
        inter = ", ".join(
            f"{i.label}({i.confidence:.2f})" for i in obs.interactions
        ) or "—"
        lines.append(f"- **{_tc(obs.t, fps)}** {obs.description}  ·  _{inter}_")
    return "\n".join(lines) + "\n"


def write_credits(result: AnalysisResult, outdir: str | Path) -> Path:
    """Write CREDITS.md — attribution for any non-CC0 sound actually used."""
    outdir = Path(outdir)
    used: dict[str, str] = {}
    for c in result.cues:
        if c.sfx and c.sfx.attribution:
            used[c.sfx.asset_id] = f"- {c.sfx.name}: {c.sfx.attribution}"

    lines = ["# Credits", ""]
    if used:
        lines += [
            "The following sounds require attribution under their licenses:",
            "",
            *sorted(used.values()),
            "",
        ]
    else:
        lines += [
            "All sounds used in this project are CC0 / public-domain and require no "
            "attribution. Provenance is tracked in the SFX library manifest.",
            "",
        ]
    lines.append("_Generated by foley-forge. Verify each license before commercial use "
                 "(see the project NOTICE)._")
    path = outdir / "CREDITS.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
